### ISSUE TITLE
HowTo outdated?

### ISSUE THREAD

**Issue by neilyoung** [aminjam/Redis.AspNet.Identity#3]
Hi,

I did successfully use your Redis ASPNetIdentity from a Nancy project from scratch, but the How To regarding MVC 5 seems to be outdated. Do you have a step by step tutorial, which works?

Regards

**Comment by aminjam** [comment]
The API's may have changed. I don't have any new updates. There will be a new release after vNext is published. If you could figure out the problem, I'd be happy to accept a pull-request to update the doc for everyone.

**Comment by neilyoung** [comment]
I think it is not only done with a
